# Generated by Django 5.0.6 on 2024-06-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employee_dept_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employee_dept'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employee_role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
