# Generated by Django 5.0.6 on 2024-06-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_branch_branch_details_branch_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_details',
            name='area',
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name='branch_details',
            name='floor',
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name='branch_employees',
            name='employee_nos',
            field=models.IntegerField(verbose_name=10000),
        ),
    ]
