# Generated by Django 5.0.6 on 2024-06-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_branch_details_area_alter_branch_details_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Branch_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch_details'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Branch_employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch_employees'),
        ),
        migrations.AlterField(
            model_name='branch_details',
            name='area',
            field=models.IntegerField(null=True, verbose_name=100),
        ),
        migrations.AlterField(
            model_name='branch_details',
            name='floor',
            field=models.IntegerField(null=True, verbose_name=100),
        ),
        migrations.AlterField(
            model_name='branch_employees',
            name='employee_email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='branch_employees',
            name='employee_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch_employees',
            name='employee_nos',
            field=models.IntegerField(null=True, verbose_name=10000),
        ),
    ]
