# Generated by Django 5.0.6 on 2024-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_branch_detail_branch_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_detail',
            name='floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch_employee',
            name='employee_nos',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
