# Generated by Django 5.0.6 on 2024-06-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_branch_detail_floor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch_detail',
            new_name='Branch_floor',
        ),
    ]
