# Generated by Django 5.0.6 on 2024-06-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_branch_detail_branch_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Branch_details',
            new_name='Branch_floor',
        ),
    ]
