# Generated by Django 5.0.6 on 2024-06-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_employee_email2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email2',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
